# Generated by Django 4.2.23 on 2025-06-30 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('endereco', models.TextField(blank=True)),
                ('peso_inicial', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura em metros', max_digits=4)),
                ('objetivo', models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('ganho_peso', 'Ganho de Peso'), ('hipertrofia', 'Hipertrofia'), ('definicao', 'Definição'), ('resistencia', 'Resistência'), ('reabilitacao', 'Reabilitação'), ('condicionamento', 'Condicionamento Físico'), ('outro', 'Outro')], max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais, histórico médico, etc.')),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_foto', models.DateField(default=django.utils.timezone.now)),
                ('tipo_foto', models.CharField(choices=[('frente', 'Frente'), ('lado', 'Lado'), ('costas', 'Costas'), ('outro', 'Outro')], max_length=10)),
                ('foto', models.ImageField(upload_to='progresso/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_progresso', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Foto de Progresso',
                'verbose_name_plural': 'Fotos de Progresso',
                'ordering': ['-data_foto'],
            },
        ),
        migrations.CreateModel(
            name='MedidasCorporais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_medicao', models.DateField(default=django.utils.timezone.now)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pescoco', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('torax', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Medidas Corporais',
                'verbose_name_plural': 'Medidas Corporais',
                'ordering': ['-data_medicao'],
                'unique_together': {('aluno', 'data_medicao')},
            },
        ),
    ]
