# Generated by Django 4.2.23 on 2025-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_semana_treino',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana fixo para treino', null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horario_treino',
            field=models.TimeField(blank=True, help_text='Horário fixo para treino', null=True),
        ),
    ]
