# Generated by Django 4.2.23 on 2025-07-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_dia_semana_treino_aluno_horario_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='objetivo',
            field=models.CharField(choices=[('saude_geral', 'Melhorar saúde geral'), ('emagrecimento', 'Emagrecimento'), ('hipertrofia', 'Hipertrofia')], max_length=20),
        ),
    ]
