# Generated by Django 4.2.23 on 2025-06-30 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('conteudo_html', models.TextField(help_text='Código HTML do template')),
                ('css_personalizado', models.TextField(blank=True, help_text='CSS personalizado para o template')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatório',
            },
        ),
        migrations.CreateModel(
            name='TipoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('template_filename', models.CharField(help_text='Nome do template HTML', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('incluir_graficos', models.BooleanField(default=True)),
                ('incluir_fotos', models.BooleanField(default=True)),
                ('incluir_medidas', models.BooleanField(default=True)),
                ('incluir_frequencia', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Relatório',
                'verbose_name_plural': 'Tipos de Relatório',
            },
        ),
        migrations.CreateModel(
            name='RelatorioProgresso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizado', 'Período Personalizado')], max_length=15)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('gerando', 'Gerando'), ('concluido', 'Concluído'), ('erro', 'Erro na Geração'), ('enviado', 'Enviado')], default='gerando', max_length=15)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('peso_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diferenca_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_treinos', models.IntegerField(default=0)),
                ('percentual_frequencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observacoes', models.TextField(blank=True)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_progresso', to='alunos.aluno')),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_gerados', to=settings.AUTH_USER_MODEL)),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.tiporelatorio')),
            ],
            options={
                'verbose_name': 'Relatório de Progresso',
                'verbose_name_plural': 'Relatórios de Progresso',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email_compartilhado', models.EmailField(blank=True, max_length=254)),
                ('data_expiracao', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='ativo', max_length=10)),
                ('acessos', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='relatorios.relatorioprogresso')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Relatório',
                'verbose_name_plural': 'Compartilhamentos de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='EstatisticaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('ano', models.IntegerField()),
                ('total_relatorios_gerados', models.IntegerField(default=0)),
                ('total_relatorios_enviados', models.IntegerField(default=0)),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_compartilhamentos', models.IntegerField(default=0)),
                ('relatorio_mais_gerado', models.CharField(blank=True, max_length=200)),
                ('periodo_mais_usado', models.CharField(blank=True, max_length=15)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatística de Relatório',
                'verbose_name_plural': 'Estatísticas de Relatórios',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('personal_trainer', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='DadosRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('medidas_json', models.JSONField(blank=True, help_text='Medidas corporais em formato JSON', null=True)),
                ('treinos_realizados', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='relatorios.relatorioprogresso')),
            ],
            options={
                'verbose_name': 'Dados do Relatório',
                'verbose_name_plural': 'Dados dos Relatórios',
                'ordering': ['data'],
                'unique_together': {('relatorio', 'data')},
            },
        ),
    ]
