# Generated by Django 4.2.23 on 2025-06-30 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('ano', models.IntegerField()),
                ('total_aulas_agendadas', models.IntegerField(default=0)),
                ('total_presencas', models.IntegerField(default=0)),
                ('total_faltas', models.IntegerField(default=0)),
                ('total_faltas_justificadas', models.IntegerField(default=0)),
                ('percentual_frequencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_frequencia', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Relatório de Frequência',
                'verbose_name_plural': 'Relatórios de Frequência',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('aluno', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(default=django.utils.timezone.now)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('falta_justificada', 'Falta Justificada'), ('cancelado', 'Cancelado')], max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a aula ou falta')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_presenca', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'ordering': ['-data_aula', 'horario_inicio'],
                'unique_together': {('aluno', 'data_aula', 'horario_inicio')},
            },
        ),
        migrations.CreateModel(
            name='AgendaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('remarcado', 'Remarcado')], default='agendado', max_length=15)),
                ('tipo_treino', models.CharField(blank=True, help_text='Ex: Treino A, Avaliação, etc.', max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_agendadas', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Agendamento de Aula',
                'verbose_name_plural': 'Agendamentos de Aulas',
                'ordering': ['data_aula', 'horario_inicio'],
                'unique_together': {('aluno', 'data_aula', 'horario_inicio')},
            },
        ),
    ]
