# Generated by Django 4.2.23 on 2025-06-30 19:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor personalizado, se diferente do plano', max_digits=8, null=True)),
                ('dia_vencimento', models.IntegerField(default=5, help_text='Dia do mês para vencimento')),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Contrato do Aluno',
                'verbose_name_plural': 'Contratos dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('ano_referencia', models.IntegerField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada'), ('parcial', 'Paga Parcialmente')], default='pendente', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='alunos.aluno')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='financeiro.contratoaluno')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'unique_together': {('aluno', 'mes_referencia', 'ano_referencia')},
            },
        ),
        migrations.CreateModel(
            name='PlanoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Plano Básico, Plano Premium', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aulas_incluidas', models.IntegerField(help_text='Número de aulas incluídas no plano')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano de Mensalidade',
                'verbose_name_plural': 'Planos de Mensalidade',
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('ano', models.IntegerField()),
                ('total_faturado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_recebido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_pendente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_atrasado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('numero_alunos_ativos', models.IntegerField(default=0)),
                ('numero_faturas_pagas', models.IntegerField(default=0)),
                ('numero_faturas_pendentes', models.IntegerField(default=0)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório Financeiro',
                'verbose_name_plural': 'Relatórios Financeiros',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto'), ('outro', 'Outro')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.fatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddField(
            model_name='contratoaluno',
            name='plano_mensalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.planomensalidade'),
        ),
    ]
