# Generated by Django 4.2.23 on 2025-06-30 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('template_titulo', models.CharField(help_text='Template do título da notificação', max_length=200)),
                ('template_mensagem', models.TextField(help_text='Template da mensagem da notificação')),
                ('ativo', models.BooleanField(default=True)),
                ('enviar_email', models.BooleanField(default=False)),
                ('enviar_whatsapp', models.BooleanField(default=False)),
                ('enviar_sistema', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificação',
                'verbose_name_plural': 'Tipos de Notificação',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('pagamento_vencido', 'Pagamento Vencido'), ('pagamento_vence_hoje', 'Pagamento Vence Hoje'), ('pagamento_vence_amanha', 'Pagamento Vence Amanhã'), ('pagamento_vence_3_dias', 'Pagamento Vence em 3 Dias'), ('aniversario_aluno', 'Aniversário do Aluno'), ('novo_relatorio_disponivel', 'Novo Relatório Disponível'), ('treino_agendado', 'Lembrete de Treino'), ('falta_frequente', 'Aluno com Muitas Faltas')], max_length=30, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('antecedencia_dias', models.IntegerField(default=0, help_text='Dias de antecedência para envio')),
                ('horario_envio', models.TimeField(default=datetime.time(19, 32, 47, 839687), help_text='Horário preferencial para envio')),
                ('apenas_alunos_ativos', models.BooleanField(default=True)),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Notificação Automática',
                'verbose_name_plural': 'Notificações Automáticas',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('lida', 'Lida'), ('erro', 'Erro no Envio'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('enviado_email', models.BooleanField(default=False)),
                ('enviado_whatsapp', models.BooleanField(default=False)),
                ('enviado_sistema', models.BooleanField(default=False)),
                ('erro_envio', models.TextField(blank=True, help_text='Detalhes do erro, se houver')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='alunos.aluno')),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='notificacoes.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_destino', models.CharField(max_length=20)),
                ('mensagem_enviada', models.TextField()),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('pendente', 'Pendente')], max_length=10)),
                ('response_api', models.JSONField(blank=True, help_text='Resposta da API do ChatPro', null=True)),
                ('tentativas', models.IntegerField(default=1)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_whatsapp', to='notificacoes.notificacao')),
            ],
            options={
                'verbose_name': 'Log WhatsApp',
                'verbose_name_plural': 'Logs WhatsApp',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_email', models.BooleanField(default=True)),
                ('receber_whatsapp', models.BooleanField(default=True)),
                ('receber_lembrete_pagamento', models.BooleanField(default=True)),
                ('receber_lembrete_treino', models.BooleanField(default=True)),
                ('receber_relatorio_progresso', models.BooleanField(default=True)),
                ('horario_preferencial', models.TimeField(default=datetime.time(19, 32, 47, 848327))),
                ('dias_antecedencia_pagamento', models.IntegerField(default=3)),
                ('email_alternativo', models.EmailField(blank=True, max_length=254)),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificacao', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificação',
            },
        ),
    ]
