# Generated by Django 4.2.23 on 2025-06-30 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='horario_preferencial',
            field=models.TimeField(default=datetime.time(21, 26, 47, 865392)),
        ),
        migrations.AlterField(
            model_name='notificacaoautomatica',
            name='horario_envio',
            field=models.TimeField(default=datetime.time(21, 26, 47, 855700), help_text='Horário preferencial para envio'),
        ),
    ]
