# Generated by Django 4.2.23 on 2025-06-30 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_alter_configuracaonotificacao_horario_preferencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='horario_preferencial',
            field=models.TimeField(default=datetime.time(22, 52, 1, 25389)),
        ),
        migrations.AlterField(
            model_name='notificacaoautomatica',
            name='horario_envio',
            field=models.TimeField(default=datetime.time(22, 52, 1, 16525), help_text='Horário preferencial para envio'),
        ),
    ]
