# Generated by Django 4.2.23 on 2025-06-30 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_alter_configuracaonotificacao_horario_preferencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='horario_preferencial',
            field=models.TimeField(default=datetime.time(23, 55, 50, 26644)),
        ),
        migrations.AlterField(
            model_name='notificacaoautomatica',
            name='horario_envio',
            field=models.TimeField(default=datetime.time(23, 55, 50, 17090), help_text='Horário preferencial para envio'),
        ),
    ]
