# Generated by Django 4.2.23 on 2025-07-01 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0006_alter_configuracaonotificacao_horario_preferencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiponotificacao',
            name='cor',
            field=models.CharField(default='#6B7280', help_text='Cor hexadecimal para identificação visual', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='horario_preferencial',
            field=models.TimeField(default=datetime.time(2, 51, 30, 294896)),
        ),
        migrations.AlterField(
            model_name='notificacaoautomatica',
            name='horario_envio',
            field=models.TimeField(default=datetime.time(2, 51, 30, 286423), help_text='Horário preferencial para envio'),
        ),
        migrations.AlterField(
            model_name='tiponotificacao',
            name='template_mensagem',
            field=models.TextField(blank=True, help_text='Template da mensagem da notificação'),
        ),
        migrations.AlterField(
            model_name='tiponotificacao',
            name='template_titulo',
            field=models.CharField(blank=True, help_text='Template do título da notificação', max_length=200),
        ),
    ]
