# Generated by Django 4.2.23 on 2025-06-30 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('grupo_muscular', models.CharField(choices=[('peito', 'Peito'), ('costas', 'Costas'), ('ombros', 'Ombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('quadriceps', 'Quadríceps'), ('posterior', 'Posterior de Coxa'), ('gluteos', 'Glúteos'), ('panturrilha', 'Panturrilha'), ('abdomen', 'Abdômen'), ('cardio', 'Cardio'), ('funcional', 'Funcional')], max_length=20)),
                ('categoria', models.CharField(choices=[('forca', 'Força'), ('cardio', 'Cardio'), ('flexibilidade', 'Flexibilidade'), ('funcional', 'Funcional')], max_length=20)),
                ('instrucoes', models.TextField(blank=True, help_text='Instruções de execução')),
                ('video_url', models.URLField(blank=True, help_text='Link para vídeo demonstrativo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='exercicios/')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Ordem de execução no treino')),
                ('series', models.IntegerField(help_text='Número de séries')),
                ('repeticoes', models.CharField(help_text='Ex: 12-15, até a falha, 30 seg', max_length=50)),
                ('carga', models.CharField(blank=True, help_text='Ex: 20kg, corpo livre', max_length=50)),
                ('tempo_descanso', models.CharField(blank=True, help_text='Tempo de descanso entre séries', max_length=50)),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
            ],
            options={
                'verbose_name': 'Exercício do Treino',
                'verbose_name_plural': 'Exercícios do Treino',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do plano de treino', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_treino', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Plano de Treino',
                'verbose_name_plural': 'Planos de Treino',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TreinoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('nome', models.CharField(help_text='Ex: Treino A - Peito e Tríceps', max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo estimado em minutos', null=True)),
                ('plano_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_diarios', to='treinos.planotreino')),
            ],
            options={
                'verbose_name': 'Treino Diário',
                'verbose_name_plural': 'Treinos Diários',
                'ordering': ['dia_semana'],
                'unique_together': {('plano_treino', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='RegistroTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tempo_total', models.IntegerField(blank=True, help_text='Tempo total em minutos', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a execução do treino')),
                ('avaliacoes', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Avaliação de 1 a 5', null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_treino', to='alunos.aluno')),
                ('treino_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='treinos.treinodiario')),
            ],
            options={
                'verbose_name': 'Registro de Treino',
                'verbose_name_plural': 'Registros de Treino',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_executadas', models.IntegerField()),
                ('repeticoes_executadas', models.CharField(help_text='Repetições por série, separadas por vírgula', max_length=200)),
                ('carga_utilizada', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('exercicio_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exerciciotreino')),
                ('registro_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_executados', to='treinos.registrotreino')),
            ],
            options={
                'verbose_name': 'Registro de Exercício',
                'verbose_name_plural': 'Registros de Exercícios',
            },
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='treino_diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treinodiario'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciciotreino',
            unique_together={('treino_diario', 'ordem')},
        ),
    ]
