# Generated by Django 4.2.23 on 2025-06-30 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planotreino',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Plano de Treino', 'verbose_name_plural': 'Planos de Treino'},
        ),
        migrations.AddField(
            model_name='exercicio',
            name='equipamento',
            field=models.CharField(choices=[('livre', 'Peso Livre'), ('maquina', 'Máquina'), ('cabo', 'Cabo/Polia'), ('corporal', 'Peso Corporal'), ('funcional', 'Funcional'), ('cardio', 'Cardio'), ('outro', 'Outro')], default='livre', max_length=20),
        ),
        migrations.AddField(
            model_name='planotreino',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planotreino',
            name='duracao_semanas',
            field=models.IntegerField(default=4, help_text='Duração em semanas'),
        ),
        migrations.AddField(
            model_name='planotreino',
            name='personal_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treinodiario',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treinodiario',
            name='plano_treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_treino', to='treinos.planotreino'),
        ),
    ]
